//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consume_Services.KeyReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KeyReference.KeyServicesSoap")]
    public interface KeyServicesSoap {
        
        // CODEGEN: Generating message contract since element name PartNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetImeiKey", ReplyAction="*")]
        Consume_Services.KeyReference.GetImeiKeyResponse GetImeiKey(Consume_Services.KeyReference.GetImeiKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetImeiKey", ReplyAction="*")]
        System.Threading.Tasks.Task<Consume_Services.KeyReference.GetImeiKeyResponse> GetImeiKeyAsync(Consume_Services.KeyReference.GetImeiKeyRequest request);
        
        // CODEGEN: Generating message contract since element name PartNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMacKey", ReplyAction="*")]
        Consume_Services.KeyReference.GetMacKeyResponse GetMacKey(Consume_Services.KeyReference.GetMacKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMacKey", ReplyAction="*")]
        System.Threading.Tasks.Task<Consume_Services.KeyReference.GetMacKeyResponse> GetMacKeyAsync(Consume_Services.KeyReference.GetMacKeyRequest request);
        
        // CODEGEN: Generating message contract since element name PartNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetKeybox", ReplyAction="*")]
        Consume_Services.KeyReference.GetKeyboxResponse GetKeybox(Consume_Services.KeyReference.GetKeyboxRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetKeybox", ReplyAction="*")]
        System.Threading.Tasks.Task<Consume_Services.KeyReference.GetKeyboxResponse> GetKeyboxAsync(Consume_Services.KeyReference.GetKeyboxRequest request);
        
        // CODEGEN: Generating message contract since element name PartNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAttestationKey", ReplyAction="*")]
        Consume_Services.KeyReference.GetAttestationKeyResponse GetAttestationKey(Consume_Services.KeyReference.GetAttestationKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAttestationKey", ReplyAction="*")]
        System.Threading.Tasks.Task<Consume_Services.KeyReference.GetAttestationKeyResponse> GetAttestationKeyAsync(Consume_Services.KeyReference.GetAttestationKeyRequest request);
        
        // CODEGEN: Generating message contract since element name PartNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReserveImeiKey", ReplyAction="*")]
        Consume_Services.KeyReference.ReserveImeiKeyResponse ReserveImeiKey(Consume_Services.KeyReference.ReserveImeiKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReserveImeiKey", ReplyAction="*")]
        System.Threading.Tasks.Task<Consume_Services.KeyReference.ReserveImeiKeyResponse> ReserveImeiKeyAsync(Consume_Services.KeyReference.ReserveImeiKeyRequest request);
        
        // CODEGEN: Generating message contract since element name PartNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReserveMacKey", ReplyAction="*")]
        Consume_Services.KeyReference.ReserveMacKeyResponse ReserveMacKey(Consume_Services.KeyReference.ReserveMacKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReserveMacKey", ReplyAction="*")]
        System.Threading.Tasks.Task<Consume_Services.KeyReference.ReserveMacKeyResponse> ReserveMacKeyAsync(Consume_Services.KeyReference.ReserveMacKeyRequest request);
        
        // CODEGEN: Generating message contract since element name PartNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReserveKeybox", ReplyAction="*")]
        Consume_Services.KeyReference.ReserveKeyboxResponse ReserveKeybox(Consume_Services.KeyReference.ReserveKeyboxRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReserveKeybox", ReplyAction="*")]
        System.Threading.Tasks.Task<Consume_Services.KeyReference.ReserveKeyboxResponse> ReserveKeyboxAsync(Consume_Services.KeyReference.ReserveKeyboxRequest request);
        
        // CODEGEN: Generating message contract since element name PartNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReserveAttestationKey", ReplyAction="*")]
        Consume_Services.KeyReference.ReserveAttestationKeyResponse ReserveAttestationKey(Consume_Services.KeyReference.ReserveAttestationKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReserveAttestationKey", ReplyAction="*")]
        System.Threading.Tasks.Task<Consume_Services.KeyReference.ReserveAttestationKeyResponse> ReserveAttestationKeyAsync(Consume_Services.KeyReference.ReserveAttestationKeyRequest request);
        
        // CODEGEN: Generating message contract since element name PartNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetImeiKeyByWoID", ReplyAction="*")]
        Consume_Services.KeyReference.GetImeiKeyByWoIDResponse GetImeiKeyByWoID(Consume_Services.KeyReference.GetImeiKeyByWoIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetImeiKeyByWoID", ReplyAction="*")]
        System.Threading.Tasks.Task<Consume_Services.KeyReference.GetImeiKeyByWoIDResponse> GetImeiKeyByWoIDAsync(Consume_Services.KeyReference.GetImeiKeyByWoIDRequest request);
        
        // CODEGEN: Generating message contract since element name PartNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMacKeyByWoID", ReplyAction="*")]
        Consume_Services.KeyReference.GetMacKeyByWoIDResponse GetMacKeyByWoID(Consume_Services.KeyReference.GetMacKeyByWoIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMacKeyByWoID", ReplyAction="*")]
        System.Threading.Tasks.Task<Consume_Services.KeyReference.GetMacKeyByWoIDResponse> GetMacKeyByWoIDAsync(Consume_Services.KeyReference.GetMacKeyByWoIDRequest request);
        
        // CODEGEN: Generating message contract since element name PartNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetKeyBoxKeyByWoID", ReplyAction="*")]
        Consume_Services.KeyReference.GetKeyBoxKeyByWoIDResponse GetKeyBoxKeyByWoID(Consume_Services.KeyReference.GetKeyBoxKeyByWoIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetKeyBoxKeyByWoID", ReplyAction="*")]
        System.Threading.Tasks.Task<Consume_Services.KeyReference.GetKeyBoxKeyByWoIDResponse> GetKeyBoxKeyByWoIDAsync(Consume_Services.KeyReference.GetKeyBoxKeyByWoIDRequest request);
        
        // CODEGEN: Generating message contract since element name PartNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAttestationKeyByWoID", ReplyAction="*")]
        Consume_Services.KeyReference.GetAttestationKeyByWoIDResponse GetAttestationKeyByWoID(Consume_Services.KeyReference.GetAttestationKeyByWoIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAttestationKeyByWoID", ReplyAction="*")]
        System.Threading.Tasks.Task<Consume_Services.KeyReference.GetAttestationKeyByWoIDResponse> GetAttestationKeyByWoIDAsync(Consume_Services.KeyReference.GetAttestationKeyByWoIDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetImeiKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetImeiKey", Namespace="http://tempuri.org/", Order=0)]
        public Consume_Services.KeyReference.GetImeiKeyRequestBody Body;
        
        public GetImeiKeyRequest() {
        }
        
        public GetImeiKeyRequest(Consume_Services.KeyReference.GetImeiKeyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetImeiKeyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PartNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string requiredQty;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string WorkOrderID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ProductID;
        
        public GetImeiKeyRequestBody() {
        }
        
        public GetImeiKeyRequestBody(string PartNo, string requiredQty, string WorkOrderID, string ProductID) {
            this.PartNo = PartNo;
            this.requiredQty = requiredQty;
            this.WorkOrderID = WorkOrderID;
            this.ProductID = ProductID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetImeiKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetImeiKeyResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consume_Services.KeyReference.GetImeiKeyResponseBody Body;
        
        public GetImeiKeyResponse() {
        }
        
        public GetImeiKeyResponse(Consume_Services.KeyReference.GetImeiKeyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetImeiKeyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetImeiKeyResult;
        
        public GetImeiKeyResponseBody() {
        }
        
        public GetImeiKeyResponseBody(string GetImeiKeyResult) {
            this.GetImeiKeyResult = GetImeiKeyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMacKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMacKey", Namespace="http://tempuri.org/", Order=0)]
        public Consume_Services.KeyReference.GetMacKeyRequestBody Body;
        
        public GetMacKeyRequest() {
        }
        
        public GetMacKeyRequest(Consume_Services.KeyReference.GetMacKeyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMacKeyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PartNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string requiredQty;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string WorkOrderID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ProductID;
        
        public GetMacKeyRequestBody() {
        }
        
        public GetMacKeyRequestBody(string PartNo, string requiredQty, string WorkOrderID, string ProductID) {
            this.PartNo = PartNo;
            this.requiredQty = requiredQty;
            this.WorkOrderID = WorkOrderID;
            this.ProductID = ProductID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMacKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMacKeyResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consume_Services.KeyReference.GetMacKeyResponseBody Body;
        
        public GetMacKeyResponse() {
        }
        
        public GetMacKeyResponse(Consume_Services.KeyReference.GetMacKeyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMacKeyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMacKeyResult;
        
        public GetMacKeyResponseBody() {
        }
        
        public GetMacKeyResponseBody(string GetMacKeyResult) {
            this.GetMacKeyResult = GetMacKeyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetKeyboxRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetKeybox", Namespace="http://tempuri.org/", Order=0)]
        public Consume_Services.KeyReference.GetKeyboxRequestBody Body;
        
        public GetKeyboxRequest() {
        }
        
        public GetKeyboxRequest(Consume_Services.KeyReference.GetKeyboxRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetKeyboxRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PartNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string requiredQty;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string WorkOrderID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ProductID;
        
        public GetKeyboxRequestBody() {
        }
        
        public GetKeyboxRequestBody(string PartNo, string requiredQty, string WorkOrderID, string ProductID) {
            this.PartNo = PartNo;
            this.requiredQty = requiredQty;
            this.WorkOrderID = WorkOrderID;
            this.ProductID = ProductID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetKeyboxResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetKeyboxResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consume_Services.KeyReference.GetKeyboxResponseBody Body;
        
        public GetKeyboxResponse() {
        }
        
        public GetKeyboxResponse(Consume_Services.KeyReference.GetKeyboxResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetKeyboxResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetKeyboxResult;
        
        public GetKeyboxResponseBody() {
        }
        
        public GetKeyboxResponseBody(string GetKeyboxResult) {
            this.GetKeyboxResult = GetKeyboxResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAttestationKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAttestationKey", Namespace="http://tempuri.org/", Order=0)]
        public Consume_Services.KeyReference.GetAttestationKeyRequestBody Body;
        
        public GetAttestationKeyRequest() {
        }
        
        public GetAttestationKeyRequest(Consume_Services.KeyReference.GetAttestationKeyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAttestationKeyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PartNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string requiredQty;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string WorkOrderID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ProductID;
        
        public GetAttestationKeyRequestBody() {
        }
        
        public GetAttestationKeyRequestBody(string PartNo, string requiredQty, string WorkOrderID, string ProductID) {
            this.PartNo = PartNo;
            this.requiredQty = requiredQty;
            this.WorkOrderID = WorkOrderID;
            this.ProductID = ProductID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAttestationKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAttestationKeyResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consume_Services.KeyReference.GetAttestationKeyResponseBody Body;
        
        public GetAttestationKeyResponse() {
        }
        
        public GetAttestationKeyResponse(Consume_Services.KeyReference.GetAttestationKeyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAttestationKeyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAttestationKeyResult;
        
        public GetAttestationKeyResponseBody() {
        }
        
        public GetAttestationKeyResponseBody(string GetAttestationKeyResult) {
            this.GetAttestationKeyResult = GetAttestationKeyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReserveImeiKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReserveImeiKey", Namespace="http://tempuri.org/", Order=0)]
        public Consume_Services.KeyReference.ReserveImeiKeyRequestBody Body;
        
        public ReserveImeiKeyRequest() {
        }
        
        public ReserveImeiKeyRequest(Consume_Services.KeyReference.ReserveImeiKeyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReserveImeiKeyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PartNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string requiredQty;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string WorkOrderID;
        
        public ReserveImeiKeyRequestBody() {
        }
        
        public ReserveImeiKeyRequestBody(string PartNo, string requiredQty, string WorkOrderID) {
            this.PartNo = PartNo;
            this.requiredQty = requiredQty;
            this.WorkOrderID = WorkOrderID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReserveImeiKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReserveImeiKeyResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consume_Services.KeyReference.ReserveImeiKeyResponseBody Body;
        
        public ReserveImeiKeyResponse() {
        }
        
        public ReserveImeiKeyResponse(Consume_Services.KeyReference.ReserveImeiKeyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReserveImeiKeyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReserveImeiKeyResult;
        
        public ReserveImeiKeyResponseBody() {
        }
        
        public ReserveImeiKeyResponseBody(string ReserveImeiKeyResult) {
            this.ReserveImeiKeyResult = ReserveImeiKeyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReserveMacKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReserveMacKey", Namespace="http://tempuri.org/", Order=0)]
        public Consume_Services.KeyReference.ReserveMacKeyRequestBody Body;
        
        public ReserveMacKeyRequest() {
        }
        
        public ReserveMacKeyRequest(Consume_Services.KeyReference.ReserveMacKeyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReserveMacKeyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PartNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string requiredQty;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string WorkOrderID;
        
        public ReserveMacKeyRequestBody() {
        }
        
        public ReserveMacKeyRequestBody(string PartNo, string requiredQty, string WorkOrderID) {
            this.PartNo = PartNo;
            this.requiredQty = requiredQty;
            this.WorkOrderID = WorkOrderID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReserveMacKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReserveMacKeyResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consume_Services.KeyReference.ReserveMacKeyResponseBody Body;
        
        public ReserveMacKeyResponse() {
        }
        
        public ReserveMacKeyResponse(Consume_Services.KeyReference.ReserveMacKeyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReserveMacKeyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReserveMacKeyResult;
        
        public ReserveMacKeyResponseBody() {
        }
        
        public ReserveMacKeyResponseBody(string ReserveMacKeyResult) {
            this.ReserveMacKeyResult = ReserveMacKeyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReserveKeyboxRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReserveKeybox", Namespace="http://tempuri.org/", Order=0)]
        public Consume_Services.KeyReference.ReserveKeyboxRequestBody Body;
        
        public ReserveKeyboxRequest() {
        }
        
        public ReserveKeyboxRequest(Consume_Services.KeyReference.ReserveKeyboxRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReserveKeyboxRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PartNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string requiredQty;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string WorkOrderID;
        
        public ReserveKeyboxRequestBody() {
        }
        
        public ReserveKeyboxRequestBody(string PartNo, string requiredQty, string WorkOrderID) {
            this.PartNo = PartNo;
            this.requiredQty = requiredQty;
            this.WorkOrderID = WorkOrderID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReserveKeyboxResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReserveKeyboxResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consume_Services.KeyReference.ReserveKeyboxResponseBody Body;
        
        public ReserveKeyboxResponse() {
        }
        
        public ReserveKeyboxResponse(Consume_Services.KeyReference.ReserveKeyboxResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReserveKeyboxResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReserveKeyboxResult;
        
        public ReserveKeyboxResponseBody() {
        }
        
        public ReserveKeyboxResponseBody(string ReserveKeyboxResult) {
            this.ReserveKeyboxResult = ReserveKeyboxResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReserveAttestationKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReserveAttestationKey", Namespace="http://tempuri.org/", Order=0)]
        public Consume_Services.KeyReference.ReserveAttestationKeyRequestBody Body;
        
        public ReserveAttestationKeyRequest() {
        }
        
        public ReserveAttestationKeyRequest(Consume_Services.KeyReference.ReserveAttestationKeyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReserveAttestationKeyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PartNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string requiredQty;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string WorkOrderID;
        
        public ReserveAttestationKeyRequestBody() {
        }
        
        public ReserveAttestationKeyRequestBody(string PartNo, string requiredQty, string WorkOrderID) {
            this.PartNo = PartNo;
            this.requiredQty = requiredQty;
            this.WorkOrderID = WorkOrderID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReserveAttestationKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReserveAttestationKeyResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consume_Services.KeyReference.ReserveAttestationKeyResponseBody Body;
        
        public ReserveAttestationKeyResponse() {
        }
        
        public ReserveAttestationKeyResponse(Consume_Services.KeyReference.ReserveAttestationKeyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReserveAttestationKeyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReserveAttestationKeyResult;
        
        public ReserveAttestationKeyResponseBody() {
        }
        
        public ReserveAttestationKeyResponseBody(string ReserveAttestationKeyResult) {
            this.ReserveAttestationKeyResult = ReserveAttestationKeyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetImeiKeyByWoIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetImeiKeyByWoID", Namespace="http://tempuri.org/", Order=0)]
        public Consume_Services.KeyReference.GetImeiKeyByWoIDRequestBody Body;
        
        public GetImeiKeyByWoIDRequest() {
        }
        
        public GetImeiKeyByWoIDRequest(Consume_Services.KeyReference.GetImeiKeyByWoIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetImeiKeyByWoIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PartNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string requiredQty;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string WorkOrderID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ProductID;
        
        public GetImeiKeyByWoIDRequestBody() {
        }
        
        public GetImeiKeyByWoIDRequestBody(string PartNo, string requiredQty, string WorkOrderID, string ProductID) {
            this.PartNo = PartNo;
            this.requiredQty = requiredQty;
            this.WorkOrderID = WorkOrderID;
            this.ProductID = ProductID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetImeiKeyByWoIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetImeiKeyByWoIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consume_Services.KeyReference.GetImeiKeyByWoIDResponseBody Body;
        
        public GetImeiKeyByWoIDResponse() {
        }
        
        public GetImeiKeyByWoIDResponse(Consume_Services.KeyReference.GetImeiKeyByWoIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetImeiKeyByWoIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetImeiKeyByWoIDResult;
        
        public GetImeiKeyByWoIDResponseBody() {
        }
        
        public GetImeiKeyByWoIDResponseBody(string GetImeiKeyByWoIDResult) {
            this.GetImeiKeyByWoIDResult = GetImeiKeyByWoIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMacKeyByWoIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMacKeyByWoID", Namespace="http://tempuri.org/", Order=0)]
        public Consume_Services.KeyReference.GetMacKeyByWoIDRequestBody Body;
        
        public GetMacKeyByWoIDRequest() {
        }
        
        public GetMacKeyByWoIDRequest(Consume_Services.KeyReference.GetMacKeyByWoIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMacKeyByWoIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PartNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string requiredQty;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string WorkOrderID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ProductID;
        
        public GetMacKeyByWoIDRequestBody() {
        }
        
        public GetMacKeyByWoIDRequestBody(string PartNo, string requiredQty, string WorkOrderID, string ProductID) {
            this.PartNo = PartNo;
            this.requiredQty = requiredQty;
            this.WorkOrderID = WorkOrderID;
            this.ProductID = ProductID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMacKeyByWoIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMacKeyByWoIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consume_Services.KeyReference.GetMacKeyByWoIDResponseBody Body;
        
        public GetMacKeyByWoIDResponse() {
        }
        
        public GetMacKeyByWoIDResponse(Consume_Services.KeyReference.GetMacKeyByWoIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMacKeyByWoIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMacKeyByWoIDResult;
        
        public GetMacKeyByWoIDResponseBody() {
        }
        
        public GetMacKeyByWoIDResponseBody(string GetMacKeyByWoIDResult) {
            this.GetMacKeyByWoIDResult = GetMacKeyByWoIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetKeyBoxKeyByWoIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetKeyBoxKeyByWoID", Namespace="http://tempuri.org/", Order=0)]
        public Consume_Services.KeyReference.GetKeyBoxKeyByWoIDRequestBody Body;
        
        public GetKeyBoxKeyByWoIDRequest() {
        }
        
        public GetKeyBoxKeyByWoIDRequest(Consume_Services.KeyReference.GetKeyBoxKeyByWoIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetKeyBoxKeyByWoIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PartNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string requiredQty;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string WorkOrderID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ProductID;
        
        public GetKeyBoxKeyByWoIDRequestBody() {
        }
        
        public GetKeyBoxKeyByWoIDRequestBody(string PartNo, string requiredQty, string WorkOrderID, string ProductID) {
            this.PartNo = PartNo;
            this.requiredQty = requiredQty;
            this.WorkOrderID = WorkOrderID;
            this.ProductID = ProductID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetKeyBoxKeyByWoIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetKeyBoxKeyByWoIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consume_Services.KeyReference.GetKeyBoxKeyByWoIDResponseBody Body;
        
        public GetKeyBoxKeyByWoIDResponse() {
        }
        
        public GetKeyBoxKeyByWoIDResponse(Consume_Services.KeyReference.GetKeyBoxKeyByWoIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetKeyBoxKeyByWoIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetKeyBoxKeyByWoIDResult;
        
        public GetKeyBoxKeyByWoIDResponseBody() {
        }
        
        public GetKeyBoxKeyByWoIDResponseBody(string GetKeyBoxKeyByWoIDResult) {
            this.GetKeyBoxKeyByWoIDResult = GetKeyBoxKeyByWoIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAttestationKeyByWoIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAttestationKeyByWoID", Namespace="http://tempuri.org/", Order=0)]
        public Consume_Services.KeyReference.GetAttestationKeyByWoIDRequestBody Body;
        
        public GetAttestationKeyByWoIDRequest() {
        }
        
        public GetAttestationKeyByWoIDRequest(Consume_Services.KeyReference.GetAttestationKeyByWoIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAttestationKeyByWoIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PartNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string requiredQty;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string WorkOrderID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ProductID;
        
        public GetAttestationKeyByWoIDRequestBody() {
        }
        
        public GetAttestationKeyByWoIDRequestBody(string PartNo, string requiredQty, string WorkOrderID, string ProductID) {
            this.PartNo = PartNo;
            this.requiredQty = requiredQty;
            this.WorkOrderID = WorkOrderID;
            this.ProductID = ProductID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAttestationKeyByWoIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAttestationKeyByWoIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public Consume_Services.KeyReference.GetAttestationKeyByWoIDResponseBody Body;
        
        public GetAttestationKeyByWoIDResponse() {
        }
        
        public GetAttestationKeyByWoIDResponse(Consume_Services.KeyReference.GetAttestationKeyByWoIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAttestationKeyByWoIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAttestationKeyByWoIDResult;
        
        public GetAttestationKeyByWoIDResponseBody() {
        }
        
        public GetAttestationKeyByWoIDResponseBody(string GetAttestationKeyByWoIDResult) {
            this.GetAttestationKeyByWoIDResult = GetAttestationKeyByWoIDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KeyServicesSoapChannel : Consume_Services.KeyReference.KeyServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KeyServicesSoapClient : System.ServiceModel.ClientBase<Consume_Services.KeyReference.KeyServicesSoap>, Consume_Services.KeyReference.KeyServicesSoap {
        
        public KeyServicesSoapClient() {
        }
        
        public KeyServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KeyServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KeyServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KeyServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consume_Services.KeyReference.GetImeiKeyResponse Consume_Services.KeyReference.KeyServicesSoap.GetImeiKey(Consume_Services.KeyReference.GetImeiKeyRequest request) {
            return base.Channel.GetImeiKey(request);
        }
        
        public string GetImeiKey(string PartNo, string requiredQty, string WorkOrderID, string ProductID) {
            Consume_Services.KeyReference.GetImeiKeyRequest inValue = new Consume_Services.KeyReference.GetImeiKeyRequest();
            inValue.Body = new Consume_Services.KeyReference.GetImeiKeyRequestBody();
            inValue.Body.PartNo = PartNo;
            inValue.Body.requiredQty = requiredQty;
            inValue.Body.WorkOrderID = WorkOrderID;
            inValue.Body.ProductID = ProductID;
            Consume_Services.KeyReference.GetImeiKeyResponse retVal = ((Consume_Services.KeyReference.KeyServicesSoap)(this)).GetImeiKey(inValue);
            return retVal.Body.GetImeiKeyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consume_Services.KeyReference.GetImeiKeyResponse> Consume_Services.KeyReference.KeyServicesSoap.GetImeiKeyAsync(Consume_Services.KeyReference.GetImeiKeyRequest request) {
            return base.Channel.GetImeiKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consume_Services.KeyReference.GetImeiKeyResponse> GetImeiKeyAsync(string PartNo, string requiredQty, string WorkOrderID, string ProductID) {
            Consume_Services.KeyReference.GetImeiKeyRequest inValue = new Consume_Services.KeyReference.GetImeiKeyRequest();
            inValue.Body = new Consume_Services.KeyReference.GetImeiKeyRequestBody();
            inValue.Body.PartNo = PartNo;
            inValue.Body.requiredQty = requiredQty;
            inValue.Body.WorkOrderID = WorkOrderID;
            inValue.Body.ProductID = ProductID;
            return ((Consume_Services.KeyReference.KeyServicesSoap)(this)).GetImeiKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consume_Services.KeyReference.GetMacKeyResponse Consume_Services.KeyReference.KeyServicesSoap.GetMacKey(Consume_Services.KeyReference.GetMacKeyRequest request) {
            return base.Channel.GetMacKey(request);
        }
        
        public string GetMacKey(string PartNo, string requiredQty, string WorkOrderID, string ProductID) {
            Consume_Services.KeyReference.GetMacKeyRequest inValue = new Consume_Services.KeyReference.GetMacKeyRequest();
            inValue.Body = new Consume_Services.KeyReference.GetMacKeyRequestBody();
            inValue.Body.PartNo = PartNo;
            inValue.Body.requiredQty = requiredQty;
            inValue.Body.WorkOrderID = WorkOrderID;
            inValue.Body.ProductID = ProductID;
            Consume_Services.KeyReference.GetMacKeyResponse retVal = ((Consume_Services.KeyReference.KeyServicesSoap)(this)).GetMacKey(inValue);
            return retVal.Body.GetMacKeyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consume_Services.KeyReference.GetMacKeyResponse> Consume_Services.KeyReference.KeyServicesSoap.GetMacKeyAsync(Consume_Services.KeyReference.GetMacKeyRequest request) {
            return base.Channel.GetMacKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consume_Services.KeyReference.GetMacKeyResponse> GetMacKeyAsync(string PartNo, string requiredQty, string WorkOrderID, string ProductID) {
            Consume_Services.KeyReference.GetMacKeyRequest inValue = new Consume_Services.KeyReference.GetMacKeyRequest();
            inValue.Body = new Consume_Services.KeyReference.GetMacKeyRequestBody();
            inValue.Body.PartNo = PartNo;
            inValue.Body.requiredQty = requiredQty;
            inValue.Body.WorkOrderID = WorkOrderID;
            inValue.Body.ProductID = ProductID;
            return ((Consume_Services.KeyReference.KeyServicesSoap)(this)).GetMacKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consume_Services.KeyReference.GetKeyboxResponse Consume_Services.KeyReference.KeyServicesSoap.GetKeybox(Consume_Services.KeyReference.GetKeyboxRequest request) {
            return base.Channel.GetKeybox(request);
        }
        
        public string GetKeybox(string PartNo, string requiredQty, string WorkOrderID, string ProductID) {
            Consume_Services.KeyReference.GetKeyboxRequest inValue = new Consume_Services.KeyReference.GetKeyboxRequest();
            inValue.Body = new Consume_Services.KeyReference.GetKeyboxRequestBody();
            inValue.Body.PartNo = PartNo;
            inValue.Body.requiredQty = requiredQty;
            inValue.Body.WorkOrderID = WorkOrderID;
            inValue.Body.ProductID = ProductID;
            Consume_Services.KeyReference.GetKeyboxResponse retVal = ((Consume_Services.KeyReference.KeyServicesSoap)(this)).GetKeybox(inValue);
            return retVal.Body.GetKeyboxResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consume_Services.KeyReference.GetKeyboxResponse> Consume_Services.KeyReference.KeyServicesSoap.GetKeyboxAsync(Consume_Services.KeyReference.GetKeyboxRequest request) {
            return base.Channel.GetKeyboxAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consume_Services.KeyReference.GetKeyboxResponse> GetKeyboxAsync(string PartNo, string requiredQty, string WorkOrderID, string ProductID) {
            Consume_Services.KeyReference.GetKeyboxRequest inValue = new Consume_Services.KeyReference.GetKeyboxRequest();
            inValue.Body = new Consume_Services.KeyReference.GetKeyboxRequestBody();
            inValue.Body.PartNo = PartNo;
            inValue.Body.requiredQty = requiredQty;
            inValue.Body.WorkOrderID = WorkOrderID;
            inValue.Body.ProductID = ProductID;
            return ((Consume_Services.KeyReference.KeyServicesSoap)(this)).GetKeyboxAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consume_Services.KeyReference.GetAttestationKeyResponse Consume_Services.KeyReference.KeyServicesSoap.GetAttestationKey(Consume_Services.KeyReference.GetAttestationKeyRequest request) {
            return base.Channel.GetAttestationKey(request);
        }
        
        public string GetAttestationKey(string PartNo, string requiredQty, string WorkOrderID, string ProductID) {
            Consume_Services.KeyReference.GetAttestationKeyRequest inValue = new Consume_Services.KeyReference.GetAttestationKeyRequest();
            inValue.Body = new Consume_Services.KeyReference.GetAttestationKeyRequestBody();
            inValue.Body.PartNo = PartNo;
            inValue.Body.requiredQty = requiredQty;
            inValue.Body.WorkOrderID = WorkOrderID;
            inValue.Body.ProductID = ProductID;
            Consume_Services.KeyReference.GetAttestationKeyResponse retVal = ((Consume_Services.KeyReference.KeyServicesSoap)(this)).GetAttestationKey(inValue);
            return retVal.Body.GetAttestationKeyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consume_Services.KeyReference.GetAttestationKeyResponse> Consume_Services.KeyReference.KeyServicesSoap.GetAttestationKeyAsync(Consume_Services.KeyReference.GetAttestationKeyRequest request) {
            return base.Channel.GetAttestationKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consume_Services.KeyReference.GetAttestationKeyResponse> GetAttestationKeyAsync(string PartNo, string requiredQty, string WorkOrderID, string ProductID) {
            Consume_Services.KeyReference.GetAttestationKeyRequest inValue = new Consume_Services.KeyReference.GetAttestationKeyRequest();
            inValue.Body = new Consume_Services.KeyReference.GetAttestationKeyRequestBody();
            inValue.Body.PartNo = PartNo;
            inValue.Body.requiredQty = requiredQty;
            inValue.Body.WorkOrderID = WorkOrderID;
            inValue.Body.ProductID = ProductID;
            return ((Consume_Services.KeyReference.KeyServicesSoap)(this)).GetAttestationKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consume_Services.KeyReference.ReserveImeiKeyResponse Consume_Services.KeyReference.KeyServicesSoap.ReserveImeiKey(Consume_Services.KeyReference.ReserveImeiKeyRequest request) {
            return base.Channel.ReserveImeiKey(request);
        }
        
        public string ReserveImeiKey(string PartNo, string requiredQty, string WorkOrderID) {
            Consume_Services.KeyReference.ReserveImeiKeyRequest inValue = new Consume_Services.KeyReference.ReserveImeiKeyRequest();
            inValue.Body = new Consume_Services.KeyReference.ReserveImeiKeyRequestBody();
            inValue.Body.PartNo = PartNo;
            inValue.Body.requiredQty = requiredQty;
            inValue.Body.WorkOrderID = WorkOrderID;
            Consume_Services.KeyReference.ReserveImeiKeyResponse retVal = ((Consume_Services.KeyReference.KeyServicesSoap)(this)).ReserveImeiKey(inValue);
            return retVal.Body.ReserveImeiKeyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consume_Services.KeyReference.ReserveImeiKeyResponse> Consume_Services.KeyReference.KeyServicesSoap.ReserveImeiKeyAsync(Consume_Services.KeyReference.ReserveImeiKeyRequest request) {
            return base.Channel.ReserveImeiKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consume_Services.KeyReference.ReserveImeiKeyResponse> ReserveImeiKeyAsync(string PartNo, string requiredQty, string WorkOrderID) {
            Consume_Services.KeyReference.ReserveImeiKeyRequest inValue = new Consume_Services.KeyReference.ReserveImeiKeyRequest();
            inValue.Body = new Consume_Services.KeyReference.ReserveImeiKeyRequestBody();
            inValue.Body.PartNo = PartNo;
            inValue.Body.requiredQty = requiredQty;
            inValue.Body.WorkOrderID = WorkOrderID;
            return ((Consume_Services.KeyReference.KeyServicesSoap)(this)).ReserveImeiKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consume_Services.KeyReference.ReserveMacKeyResponse Consume_Services.KeyReference.KeyServicesSoap.ReserveMacKey(Consume_Services.KeyReference.ReserveMacKeyRequest request) {
            return base.Channel.ReserveMacKey(request);
        }
        
        public string ReserveMacKey(string PartNo, string requiredQty, string WorkOrderID) {
            Consume_Services.KeyReference.ReserveMacKeyRequest inValue = new Consume_Services.KeyReference.ReserveMacKeyRequest();
            inValue.Body = new Consume_Services.KeyReference.ReserveMacKeyRequestBody();
            inValue.Body.PartNo = PartNo;
            inValue.Body.requiredQty = requiredQty;
            inValue.Body.WorkOrderID = WorkOrderID;
            Consume_Services.KeyReference.ReserveMacKeyResponse retVal = ((Consume_Services.KeyReference.KeyServicesSoap)(this)).ReserveMacKey(inValue);
            return retVal.Body.ReserveMacKeyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consume_Services.KeyReference.ReserveMacKeyResponse> Consume_Services.KeyReference.KeyServicesSoap.ReserveMacKeyAsync(Consume_Services.KeyReference.ReserveMacKeyRequest request) {
            return base.Channel.ReserveMacKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consume_Services.KeyReference.ReserveMacKeyResponse> ReserveMacKeyAsync(string PartNo, string requiredQty, string WorkOrderID) {
            Consume_Services.KeyReference.ReserveMacKeyRequest inValue = new Consume_Services.KeyReference.ReserveMacKeyRequest();
            inValue.Body = new Consume_Services.KeyReference.ReserveMacKeyRequestBody();
            inValue.Body.PartNo = PartNo;
            inValue.Body.requiredQty = requiredQty;
            inValue.Body.WorkOrderID = WorkOrderID;
            return ((Consume_Services.KeyReference.KeyServicesSoap)(this)).ReserveMacKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consume_Services.KeyReference.ReserveKeyboxResponse Consume_Services.KeyReference.KeyServicesSoap.ReserveKeybox(Consume_Services.KeyReference.ReserveKeyboxRequest request) {
            return base.Channel.ReserveKeybox(request);
        }
        
        public string ReserveKeybox(string PartNo, string requiredQty, string WorkOrderID) {
            Consume_Services.KeyReference.ReserveKeyboxRequest inValue = new Consume_Services.KeyReference.ReserveKeyboxRequest();
            inValue.Body = new Consume_Services.KeyReference.ReserveKeyboxRequestBody();
            inValue.Body.PartNo = PartNo;
            inValue.Body.requiredQty = requiredQty;
            inValue.Body.WorkOrderID = WorkOrderID;
            Consume_Services.KeyReference.ReserveKeyboxResponse retVal = ((Consume_Services.KeyReference.KeyServicesSoap)(this)).ReserveKeybox(inValue);
            return retVal.Body.ReserveKeyboxResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consume_Services.KeyReference.ReserveKeyboxResponse> Consume_Services.KeyReference.KeyServicesSoap.ReserveKeyboxAsync(Consume_Services.KeyReference.ReserveKeyboxRequest request) {
            return base.Channel.ReserveKeyboxAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consume_Services.KeyReference.ReserveKeyboxResponse> ReserveKeyboxAsync(string PartNo, string requiredQty, string WorkOrderID) {
            Consume_Services.KeyReference.ReserveKeyboxRequest inValue = new Consume_Services.KeyReference.ReserveKeyboxRequest();
            inValue.Body = new Consume_Services.KeyReference.ReserveKeyboxRequestBody();
            inValue.Body.PartNo = PartNo;
            inValue.Body.requiredQty = requiredQty;
            inValue.Body.WorkOrderID = WorkOrderID;
            return ((Consume_Services.KeyReference.KeyServicesSoap)(this)).ReserveKeyboxAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consume_Services.KeyReference.ReserveAttestationKeyResponse Consume_Services.KeyReference.KeyServicesSoap.ReserveAttestationKey(Consume_Services.KeyReference.ReserveAttestationKeyRequest request) {
            return base.Channel.ReserveAttestationKey(request);
        }
        
        public string ReserveAttestationKey(string PartNo, string requiredQty, string WorkOrderID) {
            Consume_Services.KeyReference.ReserveAttestationKeyRequest inValue = new Consume_Services.KeyReference.ReserveAttestationKeyRequest();
            inValue.Body = new Consume_Services.KeyReference.ReserveAttestationKeyRequestBody();
            inValue.Body.PartNo = PartNo;
            inValue.Body.requiredQty = requiredQty;
            inValue.Body.WorkOrderID = WorkOrderID;
            Consume_Services.KeyReference.ReserveAttestationKeyResponse retVal = ((Consume_Services.KeyReference.KeyServicesSoap)(this)).ReserveAttestationKey(inValue);
            return retVal.Body.ReserveAttestationKeyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consume_Services.KeyReference.ReserveAttestationKeyResponse> Consume_Services.KeyReference.KeyServicesSoap.ReserveAttestationKeyAsync(Consume_Services.KeyReference.ReserveAttestationKeyRequest request) {
            return base.Channel.ReserveAttestationKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consume_Services.KeyReference.ReserveAttestationKeyResponse> ReserveAttestationKeyAsync(string PartNo, string requiredQty, string WorkOrderID) {
            Consume_Services.KeyReference.ReserveAttestationKeyRequest inValue = new Consume_Services.KeyReference.ReserveAttestationKeyRequest();
            inValue.Body = new Consume_Services.KeyReference.ReserveAttestationKeyRequestBody();
            inValue.Body.PartNo = PartNo;
            inValue.Body.requiredQty = requiredQty;
            inValue.Body.WorkOrderID = WorkOrderID;
            return ((Consume_Services.KeyReference.KeyServicesSoap)(this)).ReserveAttestationKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consume_Services.KeyReference.GetImeiKeyByWoIDResponse Consume_Services.KeyReference.KeyServicesSoap.GetImeiKeyByWoID(Consume_Services.KeyReference.GetImeiKeyByWoIDRequest request) {
            return base.Channel.GetImeiKeyByWoID(request);
        }
        
        public string GetImeiKeyByWoID(string PartNo, string requiredQty, string WorkOrderID, string ProductID) {
            Consume_Services.KeyReference.GetImeiKeyByWoIDRequest inValue = new Consume_Services.KeyReference.GetImeiKeyByWoIDRequest();
            inValue.Body = new Consume_Services.KeyReference.GetImeiKeyByWoIDRequestBody();
            inValue.Body.PartNo = PartNo;
            inValue.Body.requiredQty = requiredQty;
            inValue.Body.WorkOrderID = WorkOrderID;
            inValue.Body.ProductID = ProductID;
            Consume_Services.KeyReference.GetImeiKeyByWoIDResponse retVal = ((Consume_Services.KeyReference.KeyServicesSoap)(this)).GetImeiKeyByWoID(inValue);
            return retVal.Body.GetImeiKeyByWoIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consume_Services.KeyReference.GetImeiKeyByWoIDResponse> Consume_Services.KeyReference.KeyServicesSoap.GetImeiKeyByWoIDAsync(Consume_Services.KeyReference.GetImeiKeyByWoIDRequest request) {
            return base.Channel.GetImeiKeyByWoIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consume_Services.KeyReference.GetImeiKeyByWoIDResponse> GetImeiKeyByWoIDAsync(string PartNo, string requiredQty, string WorkOrderID, string ProductID) {
            Consume_Services.KeyReference.GetImeiKeyByWoIDRequest inValue = new Consume_Services.KeyReference.GetImeiKeyByWoIDRequest();
            inValue.Body = new Consume_Services.KeyReference.GetImeiKeyByWoIDRequestBody();
            inValue.Body.PartNo = PartNo;
            inValue.Body.requiredQty = requiredQty;
            inValue.Body.WorkOrderID = WorkOrderID;
            inValue.Body.ProductID = ProductID;
            return ((Consume_Services.KeyReference.KeyServicesSoap)(this)).GetImeiKeyByWoIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consume_Services.KeyReference.GetMacKeyByWoIDResponse Consume_Services.KeyReference.KeyServicesSoap.GetMacKeyByWoID(Consume_Services.KeyReference.GetMacKeyByWoIDRequest request) {
            return base.Channel.GetMacKeyByWoID(request);
        }
        
        public string GetMacKeyByWoID(string PartNo, string requiredQty, string WorkOrderID, string ProductID) {
            Consume_Services.KeyReference.GetMacKeyByWoIDRequest inValue = new Consume_Services.KeyReference.GetMacKeyByWoIDRequest();
            inValue.Body = new Consume_Services.KeyReference.GetMacKeyByWoIDRequestBody();
            inValue.Body.PartNo = PartNo;
            inValue.Body.requiredQty = requiredQty;
            inValue.Body.WorkOrderID = WorkOrderID;
            inValue.Body.ProductID = ProductID;
            Consume_Services.KeyReference.GetMacKeyByWoIDResponse retVal = ((Consume_Services.KeyReference.KeyServicesSoap)(this)).GetMacKeyByWoID(inValue);
            return retVal.Body.GetMacKeyByWoIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consume_Services.KeyReference.GetMacKeyByWoIDResponse> Consume_Services.KeyReference.KeyServicesSoap.GetMacKeyByWoIDAsync(Consume_Services.KeyReference.GetMacKeyByWoIDRequest request) {
            return base.Channel.GetMacKeyByWoIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consume_Services.KeyReference.GetMacKeyByWoIDResponse> GetMacKeyByWoIDAsync(string PartNo, string requiredQty, string WorkOrderID, string ProductID) {
            Consume_Services.KeyReference.GetMacKeyByWoIDRequest inValue = new Consume_Services.KeyReference.GetMacKeyByWoIDRequest();
            inValue.Body = new Consume_Services.KeyReference.GetMacKeyByWoIDRequestBody();
            inValue.Body.PartNo = PartNo;
            inValue.Body.requiredQty = requiredQty;
            inValue.Body.WorkOrderID = WorkOrderID;
            inValue.Body.ProductID = ProductID;
            return ((Consume_Services.KeyReference.KeyServicesSoap)(this)).GetMacKeyByWoIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consume_Services.KeyReference.GetKeyBoxKeyByWoIDResponse Consume_Services.KeyReference.KeyServicesSoap.GetKeyBoxKeyByWoID(Consume_Services.KeyReference.GetKeyBoxKeyByWoIDRequest request) {
            return base.Channel.GetKeyBoxKeyByWoID(request);
        }
        
        public string GetKeyBoxKeyByWoID(string PartNo, string requiredQty, string WorkOrderID, string ProductID) {
            Consume_Services.KeyReference.GetKeyBoxKeyByWoIDRequest inValue = new Consume_Services.KeyReference.GetKeyBoxKeyByWoIDRequest();
            inValue.Body = new Consume_Services.KeyReference.GetKeyBoxKeyByWoIDRequestBody();
            inValue.Body.PartNo = PartNo;
            inValue.Body.requiredQty = requiredQty;
            inValue.Body.WorkOrderID = WorkOrderID;
            inValue.Body.ProductID = ProductID;
            Consume_Services.KeyReference.GetKeyBoxKeyByWoIDResponse retVal = ((Consume_Services.KeyReference.KeyServicesSoap)(this)).GetKeyBoxKeyByWoID(inValue);
            return retVal.Body.GetKeyBoxKeyByWoIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consume_Services.KeyReference.GetKeyBoxKeyByWoIDResponse> Consume_Services.KeyReference.KeyServicesSoap.GetKeyBoxKeyByWoIDAsync(Consume_Services.KeyReference.GetKeyBoxKeyByWoIDRequest request) {
            return base.Channel.GetKeyBoxKeyByWoIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consume_Services.KeyReference.GetKeyBoxKeyByWoIDResponse> GetKeyBoxKeyByWoIDAsync(string PartNo, string requiredQty, string WorkOrderID, string ProductID) {
            Consume_Services.KeyReference.GetKeyBoxKeyByWoIDRequest inValue = new Consume_Services.KeyReference.GetKeyBoxKeyByWoIDRequest();
            inValue.Body = new Consume_Services.KeyReference.GetKeyBoxKeyByWoIDRequestBody();
            inValue.Body.PartNo = PartNo;
            inValue.Body.requiredQty = requiredQty;
            inValue.Body.WorkOrderID = WorkOrderID;
            inValue.Body.ProductID = ProductID;
            return ((Consume_Services.KeyReference.KeyServicesSoap)(this)).GetKeyBoxKeyByWoIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consume_Services.KeyReference.GetAttestationKeyByWoIDResponse Consume_Services.KeyReference.KeyServicesSoap.GetAttestationKeyByWoID(Consume_Services.KeyReference.GetAttestationKeyByWoIDRequest request) {
            return base.Channel.GetAttestationKeyByWoID(request);
        }
        
        public string GetAttestationKeyByWoID(string PartNo, string requiredQty, string WorkOrderID, string ProductID) {
            Consume_Services.KeyReference.GetAttestationKeyByWoIDRequest inValue = new Consume_Services.KeyReference.GetAttestationKeyByWoIDRequest();
            inValue.Body = new Consume_Services.KeyReference.GetAttestationKeyByWoIDRequestBody();
            inValue.Body.PartNo = PartNo;
            inValue.Body.requiredQty = requiredQty;
            inValue.Body.WorkOrderID = WorkOrderID;
            inValue.Body.ProductID = ProductID;
            Consume_Services.KeyReference.GetAttestationKeyByWoIDResponse retVal = ((Consume_Services.KeyReference.KeyServicesSoap)(this)).GetAttestationKeyByWoID(inValue);
            return retVal.Body.GetAttestationKeyByWoIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consume_Services.KeyReference.GetAttestationKeyByWoIDResponse> Consume_Services.KeyReference.KeyServicesSoap.GetAttestationKeyByWoIDAsync(Consume_Services.KeyReference.GetAttestationKeyByWoIDRequest request) {
            return base.Channel.GetAttestationKeyByWoIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consume_Services.KeyReference.GetAttestationKeyByWoIDResponse> GetAttestationKeyByWoIDAsync(string PartNo, string requiredQty, string WorkOrderID, string ProductID) {
            Consume_Services.KeyReference.GetAttestationKeyByWoIDRequest inValue = new Consume_Services.KeyReference.GetAttestationKeyByWoIDRequest();
            inValue.Body = new Consume_Services.KeyReference.GetAttestationKeyByWoIDRequestBody();
            inValue.Body.PartNo = PartNo;
            inValue.Body.requiredQty = requiredQty;
            inValue.Body.WorkOrderID = WorkOrderID;
            inValue.Body.ProductID = ProductID;
            return ((Consume_Services.KeyReference.KeyServicesSoap)(this)).GetAttestationKeyByWoIDAsync(inValue);
        }
    }
}
